import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased relative`}
      >
        {/* Vertical Framing Lines */}
        <div className="fixed left-[100px] top-0 bottom-0 w-[2px] bg-[#D1D1D1] z-50 pointer-events-none hidden lg:block" />
        <div className="fixed right-[100px] top-0 bottom-0 w-[2px] bg-[#D1D1D1] z-50 pointer-events-none hidden lg:block" />
        {children}
      </body>
    </html>
  );
}
