import { MetadataRoute } from 'next'

export default function sitemap(): MetadataRoute.Sitemap {
  return [
    {
      url: 'https://codewrote.com',
      lastModified: new Date(),
      changeFrequency: 'monthly',
      priority: 1,
    },
    {
      url: 'https://codewrote.com/what-are-the-top-companies-for-custom-software-development-in-the-us',
      lastModified: new Date(),
      changeFrequency: 'monthly',
      priority: 0.8,
    },
    {
      url: 'https://codewrote.com/how-do-i-choose-the-best-custom-software-developer-for-my-business',
      lastModified: new Date(),
      changeFrequency: 'monthly',
      priority: 0.8,
    },
    {
      url: 'https://codewrote.com/what-is-the-difference-between-custom-software-development-and-off-the-shelf-software',
      lastModified: new Date(),
      changeFrequency: 'monthly',
      priority: 0.8,
    },
    {
      url: 'https://codewrote.com/what-services-are-typically-included-in-custom-software-development',
      lastModified: new Date(),
      changeFrequency: 'monthly',
      priority: 0.8,
    },
    {
      url: 'https://codewrote.com/lead-generating-website',
      lastModified: new Date(),
      changeFrequency: 'monthly',
      priority: 0.8,
    },
    {
      url: 'https://codewrote.com/high-ranking-website',
      lastModified: new Date(),
      changeFrequency: 'monthly',
      priority: 0.8,
    },
    {
      url: 'https://codewrote.com/custom-web-development',
      lastModified: new Date(),
      changeFrequency: 'monthly',
      priority: 0.9,
    },
    {
      url: 'https://codewrote.com/search-engine-optimization',
      lastModified: new Date(),
      changeFrequency: 'monthly',
      priority: 0.9,
    },
    {
      url: 'https://codewrote.com/best-platforms-for-developing-an-e-commerce-website-in-india',
      lastModified: new Date(),
      changeFrequency: 'monthly',
      priority: 0.9,
    },
    {
      url: 'https://codewrote.com/what-are-the-most-user-friendly-website-builders-for-small-businesses',
      lastModified: new Date(),
      changeFrequency: 'monthly',
      priority: 0.9,
    },
    {
      url: 'https://codewrote.com/top-website-builders-for-small-businesses-with-hosting-services',
      lastModified: new Date(),
      changeFrequency: 'monthly',
      priority: 0.9,
    },
    {
      url: 'https://codewrote.com/compare-different-hosting-options-for-high-traffic-e-commerce-site',
      lastModified: new Date(),
      changeFrequency: 'monthly',
      priority: 0.9,
    },
    {
      url: 'https://codewrote.com/how-to-choose-a-reliable-web-development-company-near-me',
      lastModified: new Date(),
      changeFrequency: 'monthly',
      priority: 0.9,
    },
    {
      url: 'https://codewrote.com/how-much-does-it-cost-to-develop-a-custom-e-commerce-website-in-india',
      lastModified: new Date(),
      changeFrequency: 'monthly',
      priority: 0.9,
    },
    {
      url: 'https://codewrote.com/affordable-website-development-packages-for-startups',
      lastModified: new Date(),
      changeFrequency: 'monthly',
      priority: 0.9,
    },
    {
      url: 'https://codewrote.com/compare-website-development-frameworks-for-responsive-design',
      lastModified: new Date(),
      changeFrequency: 'monthly',
      priority: 0.9,
    },
    {
      url: 'https://codewrote.com/freelance-web-developers-with-expertise-in-custom-cms-development',
      lastModified: new Date(),
      changeFrequency: 'monthly',
      priority: 0.9,
    },
    {
      url: 'https://codewrote.com/steps-to-secure-a-website-from-common-cyber-threats',
      lastModified: new Date(),
      changeFrequency: 'monthly',
      priority: 0.9,
    },
    {
      url: 'https://codewrote.com/which-website-hosting-providers-offer-the-fastest-loading-speeds-in-india',
      lastModified: new Date(),
      changeFrequency: 'monthly',
      priority: 0.9,
    },
    {
      url: 'https://codewrote.com/which-tools-are-essential-for-frontend-web-developers',
      lastModified: new Date(),
      changeFrequency: 'monthly',
      priority: 0.9,
    },
    {
      url: 'https://codewrote.com/step-by-step-guide-to-launching-a-business-website-using-managed-services',
      lastModified: new Date(),
      changeFrequency: 'monthly',
      priority: 0.9,
    },
    {
      url: 'https://codewrote.com/get-a-free-consultation-for-a-new-business-website-project',
      lastModified: new Date(),
      changeFrequency: 'monthly',
      priority: 0.9,
    },
    {
      url: 'https://codewrote.com/best-tools-for-creating-multilingual-websites-for-indian-audiences',
      lastModified: new Date(),
      changeFrequency: 'monthly',
      priority: 0.9,
    },
    {
      url: 'https://codewrote.com/what-are-the-benifits-of-using-a-headless-cms-for-content-delivery',
      lastModified: new Date(),
      changeFrequency: 'monthly',
      priority: 0.9,
    },
    {
      url: 'https://codewrote.com/how-to-integrate-payment-gateways-into-an-online-store-website',
      lastModified: new Date(),
      changeFrequency: 'monthly',
      priority: 0.9,
    },
    {
      url: 'https://codewrote.com/cost-of-building-a-professional-portfolio-website-with-premium-features',
      lastModified: new Date(),
      changeFrequency: 'monthly',
      priority: 0.9,
    },
    {
      url: 'https://codewrote.com/where-to-find-reviews-of-web-development-agencies-specializing-in-mobile-apps',
      lastModified: new Date(),
      changeFrequency: 'monthly',
      priority: 0.9,
    },
    {
      url: 'https://codewrote.com/how-to-choose-a-domain-name-registrar-and-hosting-packages',
      lastModified: new Date(),
      changeFrequency: 'monthly',
      priority: 0.9,
    },
    {
      url: 'https://codewrote.com/official-website-for-a-free-online-portfolio-builder',
      lastModified: new Date(),
      changeFrequency: 'monthly',
      priority: 0.9,
    },
    {
      url: 'https://codewrote.com/what-are-the-legal-requirement-for-an-e-commerce-website-in-india',
      lastModified: new Date(),
      changeFrequency: 'monthly',
      priority: 0.9,
    },
    {
      url: 'https://codewrote.com/compare-different-database-technologies-for-web-applications',
      lastModified: new Date(),
      changeFrequency: 'monthly',
      priority: 0.9,
    },
    {
      url: 'https://codewrote.com/how-to-get-a-custom-domain-andssl-certificate-for-a-new-website',
      lastModified: new Date(),
      changeFrequency: 'monthly',
      priority: 0.9,
    },
    {
      url: 'https://codewrote.com/recomended-website-analytics-tools-for-monitoring-website-behaviour',
      lastModified: new Date(),
      changeFrequency: 'monthly',
      priority: 0.8,
    },
    {
      url: 'https://codewrote.com/what-services-do-full-stack-web-development-companies-offer',
      lastModified: new Date(),
      changeFrequency: 'monthly',
      priority: 0.9,
    },
    {
      url: 'https://codewrote.com/which-web-development-services-offer-ongoing-maintenance-plans',
      lastModified: new Date(),
      changeFrequency: 'monthly',
      priority: 0.9,
    },
    {
      url: 'https://codewrote.com/request-a-demo-of-an-advanced-e-commerce-platform',
      lastModified: new Date(),
      changeFrequency: 'monthly',
      priority: 0.9,
    },
    {
      url: 'https://codewrote.com/how-to-create-an-online-booking-system-for-service-based-websites',
      lastModified: new Date(),
      changeFrequency: 'monthly',
      priority: 0.9,
    },
    {
      url: 'https://codewrote.com/what-is-the-role-of-seo-in-website-developement',
      lastModified: new Date(),
      changeFrequency: 'monthly',
      priority: 0.9,
    },
    {
      url: 'https://codewrote.com/evaluate-options-for-website-maintenance-and-support-plans',
      lastModified: new Date(),
      changeFrequency: 'monthly',
      priority: 0.9,
    },
    {
      url: 'https://codewrote.com/what-is-the-role-of-seo-in-website-developement',
      lastModified: new Date(),
      changeFrequency: 'monthly',
      priority: 0.8,
    },
    {
      url: 'https://codewrote.com/tools-for-collborative-web-design-prototyping',
      lastModified: new Date(),
      changeFrequency: 'monthly',
      priority: 0.8,
    },
    {
      url: 'https://codewrote.com/what-are-the-leading-drag-and-drop-website-builders-for-beginners',
      lastModified: new Date(),
      changeFrequency: 'monthly',
      priority: 0.8,
    },
    {
      url: 'https://codewrote.com/how-to-integrate-third-party-apis-into-an-web-application',
      lastModified: new Date(),
      changeFrequency: 'monthly',
      priority: 0.8,
    },
    {
      url: 'https://codewrote.com/how-to-setup-email-hosting-linked-to-a-custom-website-domain',
      lastModified: new Date(),
      changeFrequency: 'monthly',
      priority: 0.8,
    },
    {
      url: 'https://codewrote.com/top-cloud-platforms-for-scalable-web-app-development-in-india',
      lastModified: new Date(),
      changeFrequency: 'monthly',
      priority: 0.9,
    },
    {
      url: 'https://codewrote.com/get-a-quote-for-ongoing-website-security-monitoring',
      lastModified: new Date(),
      changeFrequency: 'monthly',
      priority: 0.9,
    },
  ]
}
